# Generated by Django 5.1.1 on 2024-11-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_imagemodel_remove_book_title_address_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
