# Generated by Django 5.1.1 on 2024-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_remove_address_street_remove_address_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='addresses',
            field=models.ManyToManyField(to='bookmodule.address'),
        ),
    ]
