# Generated by Django 5.1.1 on 2024-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_remove_student_address_student_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
