# Generated by Django 5.1.1 on 2024-11-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0007_imagemodel_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='c',
        ),
    ]
